# Generated by Django 4.2.7 on 2024-09-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover", models.ImageField(upload_to="images/")),
                ("types", models.CharField(max_length=50)),
                ("manufacturer", models.CharField(max_length=50)),
                ("isonbase", models.BooleanField(default=False)),
                ("medonbox", models.BooleanField(default=False)),
                ("caponbox", models.BooleanField(default=False)),
                ("stronbox", models.BooleanField(default=False)),
            ],
        ),
    ]
